FROM {{ "composer-php81" | image_tag }}

USER root

# We'll need various dependencies. mysqli seems to be the only relevant dependency for core,
# but as per mediawiki-phan dockerfile, these deps should maybe be installed in a more base dockerfile
RUN {{ "php8.1-mysql" | apt_install }}

USER nobody
COPY run.sh /run.sh
ENTRYPOINT ["/run.sh"]
