#!/usr/bin/env bash
#
# Push .prom files generated by wdio-mediawiki and send them to the production
# Prometheus.
#
# See https://phabricator.wikimedia.org/T392894
set -eux -o pipefail

PROMETHEUS_GATEWAY=http://prometheus-pushgateway.discovery.wmnet/metrics/job/browsertests

# Make pattern matching no file to return null instead of itself
shopt -s nullglob

PROM_FILES=(*.prom)
if [ ${#PROM_FILES[@]} -eq 0 ]; then
    echo "Could not find any *.prom file."
fi

# curl is so terrible for this... --fail shallows any output, instead:
# * write the status code to stdout so we can check whether it is a 200
# * write the response body to stderr so it gets displayed
#
# Use || for logical OR. Single | will pipe.
# shellcheck disable=SC2266
grep -P "^(wdio_|cypress_)" -- *.prom \
    | [ 200 -eq "$(curl --silent --show-error \
                    --connect-timeout 2 \
                    --max-time 6 \
                    --fail \
                    --output /dev/stderr \
                    --write-out "%{http_code}" \
                    --data-binary @- \
                    "$PROMETHEUS_GATEWAY")" ]
