#!/usr/bin/env bash
set -e

# JJB is incompatible with Python 3.12+
#
# Ensure `python3` is less than 3.12 else force python 3.11
#
# https://www.mediawiki.org/wiki/Continuous_integration/Jenkins_job_builder#Troubleshooting
# https://bugs.launchpad.net/python-jenkins/+bug/2038855
if python3 -c 'import sys; sys.exit(1 if sys.version_info >= (3, 12) else 0)'
then
    exec python3 -m tox -qq -e jenkins-jobs -- "${@}"
else
    exec python3.11 -m tox -qq -e jenkins-jobs -- "${@}"
fi
