FROM {{ "tox-buster" | image_tag }}

ENV POETRY_HOME=/opt/poetry
USER root
RUN mkdir -p /opt/poetry \
    && chown -R nobody /opt/poetry \
    && ln -s /opt/poetry/bin/poetry /bin/poetry
USER nobody
COPY install-poetry.py /opt/poetry/install-poetry.py
RUN python3 /opt/poetry/install-poetry.py
