FROM {{ "composer-scratch" | image_tag }} as composer

FROM {{ "php84" | image_tag }}

# Install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

USER root

RUN {{ "jq" | apt_install }}

USER nobody
COPY run-test /run-test
COPY run-testpackage /run-testpackage

ENTRYPOINT ["/usr/bin/composer"]
CMD ["help"]
