FROM {{ "ci-bullseye" | image_tag }}

USER root

ADD shellcheck-backport.pref /etc/apt/preferences.d/shellcheck-backport.pref

RUN {{ "shellcheck" | apt_install }}

COPY run.sh /run.sh

USER nobody
WORKDIR /src
ENTRYPOINT ["/run.sh"]
