- hosts: localhost
  tasks:
    - name: Run a container (via kubectl)
      command:
        cmd: >-
          kubectl run {{ name | default('task', true) }}
          --attach --rm --restart=Never
          --image={{ container.image | default('docker-registry.wikimedia.org/wmfdebug:0.0.7-20260614', true) }}
          --command --
          {{ container.command }}
      when: ansible_env.KUBECONFIG is defined

    - name: Run a container (via docker run)
      command:
        cmd: >-
          docker run --name {{ name | default('task', true) }}
          --rm --init
          {{ container.image | default('docker-registry.wikimedia.org/wmfdebug:0.0.7-20260614', true) }}
          --
          {{ container.command }}
      when: ansible_env.KUBECONFIG is not defined
