FROM {{ "composer-scratch" | image_tag }} as composer

FROM {{ "php74" | image_tag }}

# Install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

# Grab our composer helper scripts
COPY --from=composer /srv/composer /srv/composer

USER root

USER nobody
COPY run.sh /run.sh
ENTRYPOINT ["/run.sh"]
