FROM {{ "ci-trixie" | image_tag }} AS build

USER root
RUN {{ "golang-go gcc libc6-dev" | apt_install }} \
    && install --owner=nobody --group=nogroup --directory /build /build/gopath

USER nobody
ENV GOPATH=/build/gopath
RUN cd /build \
    && go install github.com/bazelbuild/bazelisk@v1.29.0

FROM {{ "ci-trixie" | image_tag }}
USER root
RUN install --owner=nobody --group=nogroup --directory /var/local/bazel
COPY bazelrc /var/local/bazel/bazelrc
COPY --from=build /build/gopath/bin/bazelisk /usr/local/bin/bazelisk-real
COPY bazelisk /usr/local/bin/bazelisk

USER nobody
# In addition to showing the actual Bazel version at build time, that also
# triggers extraction of the Bazel installation under outputUserRoot. That
# saves time on future invocations.
RUN /usr/local/bin/bazelisk version
WORKDIR /src
ENTRYPOINT ["/usr/local/bin/bazelisk"]
