FROM {{ "php85" | image_tag }} as php85

FROM {{ "quibble-bookworm" | image_tag }}

ENV PHP_VERSION=8.5

USER root

# Align with SRE-provided PHP 8.5 packages (T433254).
COPY wikimedia-php85.list /etc/apt/sources.list.d/wikimedia-php85.list

#############################
#  Debian packages we need  #
#############################
{% set mediawiki_deps|replace('\n', ' ') -%}
php8.5-apcu
php8.5-bcmath
php8.5-cli
php8.5-curl
php8.5-fpm
php8.5-gd
php8.5-gmp
php8.5-intl
php8.5-ldap
php8.5-mbstring
php8.5-memcached
php8.5-mysql
php8.5-pcov
php8.5-pgsql
php8.5-sqlite3
php8.5-tidy
php8.5-uuid
php8.5-xdebug
php8.5-xml
php8.5-zip
{%- endset -%}

RUN {{ mediawiki_deps | apt_install }} \
    && /install-php-fpm-conf.sh

# Get a new, standard-across-Wikimedia-CI version of php-ast from our build, rather than using Debian's old one.
# The careful work to custom-build this is already done in the php85 image, so just re-use.
COPY --from=php85 /usr/lib/php/20250925/ast.so /usr/lib/php/20250925/ast.so
COPY --from=php85 /etc/php/8.5/cli/conf.d/20-ast.ini /etc/php/8.5/cli/conf.d/20-ast.ini

# Disable pcov by default, although the performance overhead should be minimal
RUN phpdismod pcov xdebug

# Disable XDebug by default due to its performance impact
RUN phpdismod xdebug

# Ensure the image use PHP 8.5, as that is not the default on bookworm
RUN update-alternatives --set php /usr/bin/php8.5

# Unprivileged
RUN install --directory /workspace --owner=nobody --group=nogroup
USER nobody
WORKDIR /workspace
ENTRYPOINT ["/usr/local/bin/quibble"]
