- hosts: all
  roles:
    # Collect artifacts, logs and docs from the nodes `zuul_output_dir`
    - role: fetch-output-openshift
      zuul_log_verbose: true

- hosts: localhost
  gather_facts: False
  roles:
    - role: generate-zuul-manifest
      # Tell the zuul web ui that it needs to add index.html to the
      # end of directory links.
      generate_zuul_manifest_index_links: true

    # https://zuul-ci.org/docs/zuul-jobs/latest/log-roles.html#role-upload-logs-swift
    # https://wikitech.wikimedia.org/wiki/Help:Object_storage_user_guide#Swift_API
    - role: upload-logs-swift
      zuul_log_cloud_config: "{{ wmcs_swift_api.cloud_config }}"
      zuul_log_container: artifacts
      # Swift object expiration, passed to `X-Delete-After` header
      # https://docs.openstack.org/swift/latest/overview_expiring_objects.html
      zuul_log_delete_after: 300 # seconds = 5 minutes
