# Docker image with nodejs, jsduck, and browsers installed, plus composer.

FROM {{ "composer-scratch" | image_tag }} as composer

FROM {{ "php-scratch" | image_tag }} as php-scratch

FROM {{ "sury-php" | image_tag }} as sury

## START: Copied from php81 image...
#
# Set a standard, new version of php-ast rather than using Debian's older one.
#
# We create a stage with php-dev to compile the ast extension from source. This
# is done as a multistage build to ensure it is compiled with the same version
# of PHP than the one that will be in the final image (T396312).
FROM {{ "sury-php" | image_tag }} as ast-builder

USER root
RUN {{ "php8.1-dev build-essential" | apt_install }}
RUN install --owner=nobody --group=nogroup --directory /srv/php-ast
RUN install --owner=nobody --group=nogroup --directory /srv/artifacts

USER nobody
COPY --from=php-scratch build-extension-ast /build-extension-ast
RUN cd /srv && /build-extension-ast
# Outputs: /srv/artifacts/ast.so /srv/artifacts/ast.ini

## END: Copy from php81 image...

FROM {{ "node22-test-browser" | image_tag }}

# Install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

USER root

## START: O, my kingdom for multiple inheritance!
# Copied from the sury image; keep this synchronised!

COPY --from=sury /etc/apt/trusted.gpg.d/php.gpg /etc/apt/trusted.gpg.d/php.gpg
# Sury uses https and requires lsb per https://packages.sury.org/php/README.txt
RUN {{ "apt-transport-https" | apt_install }} && \
    echo "deb https://packages.sury.org/php/ bookworm main" > /etc/apt/sources.list.d/php.list

# zip is needed for composer to install things from dist
# others are libraries/MediaWiki related
{% set packages|replace('\n', ' ') -%}
php8.1-ast
php8.1-cli
php8.1-zip
php8.1-bcmath
php8.1-curl
php8.1-dba
php8.1-gd
php8.1-gmp
php8.1-intl
php8.1-mbstring
php8.1-redis
php8.1-sqlite3
php8.1-uuid
php8.1-xml
zip
unzip
{%- endset -%}

RUN {{ packages | apt_install }}

## START: Copied from php81 image...
#
# Copy ast from the above building stage
COPY --from=ast-builder /srv/artifacts/ast.so /usr/lib/php/20210902/ast.so
COPY --from=ast-builder /srv/artifacts/ast.ini /etc/php/8.1/cli/conf.d/20-ast.ini
COPY --from=php-scratch test-ast-tokens.php /test-ast-tokens.php
RUN php /test-ast-tokens.php
## END: Copy from php81 image...

RUN {{ "jq" | apt_install }}

# phantomjs crashes when there is no DISPLAY
ENV QT_QPA_PLATFORM=offscreen

# HACK: We manually copy across composer, like all the other images that need it
# Install composer
COPY --from=composer /usr/bin/composer /usr/bin/composer

## END: O, my kingdom for multiple inheritance!

USER nobody

WORKDIR /src
ENTRYPOINT "echo 'This image does not define an entrypoint, you have to define one yourself'; exit 1"
