FROM {{ "php81" | image_tag }}

USER root

# libthai is for wikidiff2, and
# liblua5.1 and liblua5.4 are for luasandbox (configure prefers 5.1 when
# both are present, so this doesn't change what the default build links
# against -- it just makes a Lua 5.4 build possible to test too)
# lcov is coverage generation
# lcov is coverage generation
{% set packages|replace('\n', ' ') -%}
php8.1-dev
build-essential
pkg-config
libthai-dev
liblua5.1-dev
liblua5.4-dev
lcov
{%- endset -%}

RUN {{ packages | apt_install }}

USER nobody

COPY run.sh /run.sh
COPY run-coverage.sh /run-coverage.sh
ENTRYPOINT ["/run.sh"]
