#!/bin/bash
#
# diffrecursive2changelog: generate a changelog from a diff
#
# Reads from stdin the output of `diff --recursive --quiet` and processes it to
# show a changelog suitable for changes made to JJB jobs.
#
# Example
#
#  $ diff --recursive --brief ./output-parent ./output-proposed \
#    | ./utils/diff2changelog
#  Affected jobs:
#   - beta-scap-sync-world
#  Deleted jobs:
#   - beta-code-update-eqiad
#   - beta-update-databases-eqiad
#  New jobs:
#   - beta-code-update
#  $
#

set -eu -o pipefail

pgm="$(basename "$0")"

if [[ -n "${FORCE_COLOR:-}" || -t 1 ]]; then
    BLACK_BOLD='\e[0;1m'
    YELLOW='\e[33m'
    MAGENTA='\e[35m'
    CYAN='\e[36m'
    RESET='\e[0;0m'
else
    BLACK_BOLD=
    YELLOW=
    MAGENTA=
    CYAN=
    RESET=
fi

sort | while IFS= read -r line
do
    if [[ "$line" =~ ^Files\ \./output-parent/([^/]+)/config.xml\ and\ .* ]]; then
        if [[ ! -v affected_header_written ]]; then
            # shellcheck disable=SC2059
            printf "${BLACK_BOLD}Affected jobs:${RESET}\n"
            affected_header_written=1
        fi
        printf " - ${YELLOW}%s${RESET}\n" "${BASH_REMATCH[1]}"

    elif [[ "$line" =~ ^Only\ in\ ./output-parent:\ (.+) ]]; then
        if [[ ! -v deleted_header_written ]]; then
            # shellcheck disable=SC2059
            printf "${BLACK_BOLD}Deleted jobs:${RESET}\n"
            deleted_header_written=1
        fi
        printf " - ${MAGENTA}%s${RESET}\n" "${BASH_REMATCH[1]}"

    elif [[ "$line" =~ ^Only\ in\ \./output-proposed:\ (.*) ]]; then
        if [[ ! -v new_header_written ]]; then
            # shellcheck disable=SC2059
            printf "${BLACK_BOLD}New jobs:${RESET}\n"
            new_header_written=1
        fi
        printf " - ${CYAN}%s${RESET}\n" "${BASH_REMATCH[1]}"
    else
        >&2 printf "%s: unrecognized line: %s\n" "$pgm" "$line"
        if [ "$line" == "---" ]; then
            >&2 printf "%s: must invoke 'diff --recursive' with '--brief'\n" "$pgm"
        fi
        exit 2
    fi
done
