#!/bin/bash

set -eux -o pipefail

# ast v1.1.2. We use sha1 for immutability
git clone https://github.com/nikic/php-ast

pushd php-ast
git checkout --quiet 152b420ed6ca9029b47e52362916af0b25b2c7b3
git describe --tags
phpize
./configure
make
popd

mkdir -p artifacts
mv php-ast/modules/ast.so artifacts/ast.so
echo 'extension=ast.so' > artifacts/ast.ini
