#!/bin/bash

set -eux -o pipefail

git clone https://github.com/nikic/php-ast

pushd php-ast
# ast v1.1.3. We use sha1 for immutability
git checkout --quiet c2faa5d071454ba3c2d0170611e92846ca606bba
git describe --tags
phpize
./configure
make
popd

mkdir -p artifacts
mv php-ast/modules/ast.so artifacts/ast.so
echo 'extension=ast.so' > artifacts/ast.ini
