# Docker image with plain nodejs and npm.

FROM {{ "ci-buster" | image_tag }}

USER root

RUN {{ "nodejs" | apt_install }}

# Use Wikimedia's custom npm build instead of Debian's out-dated one (?)
RUN git clone --depth 1 https://gerrit.wikimedia.org/r/p/integration/npm.git /srv/npm \
    && rm -rf /srv/npm/.git \
    && ln -s /srv/npm/bin/npm-cli.js /usr/bin/npm

USER nobody

ENTRYPOINT ["npm"]
CMD ["--help"]
