# Docker image with plain nodejs and npm.

FROM {{ "ci-bullseye" | image_tag }}

USER root

RUN {{ "nodejs" | apt_install }}

# Pin our Node 12 image to npm 7.x. Official Node.js 12 tarballs come with npm 6,
# but, we upgraded npm and we're sticking to it.
RUN git clone --depth 1 https://gerrit.wikimedia.org/r/integration/npm.git -b npm-7.5.2 /srv/npm \
    && rm -rf /srv/npm/.git \
    && ln -s /srv/npm/bin/npm-cli.js /usr/bin/npm

USER nobody

ENTRYPOINT ["npm"]
CMD ["--help"]
